production:
    host: kurtmackey.couch.io
    port: 80
    database: resistor
    username: kurtmackey
    password: letmein

development:
    host: kurtmackey.couch.io
    port: 80
    database: resistor_dev
    username: kurtmackey
    password: letmein

test:
    host: kurtmackey.couch.io
    port: 80
    database: resistor_test
    username: kurtmackey
    password: letmein